/**
 * The global revenue map — which problems people already pay to solve, which
 * markets Zakai can address with today's product shape, and how money is
 * captured. This is the CEO-facing catalog exposed at /api/network/opportunity-map
 * for agents, partners, and internal prioritisation. Amounts are indicative
 * headline recoveries in minor units of the stated currency — never promises.
 */

export type MonetizationModel =
  | "success_fee"
  | "subscription"
  | "oracle_api"
  | "lead_fee"
  | "network_verification";

export type VerticalStatus = "live_agent" | "letter_pack" | "rights_only" | "planned";

export interface RevenueVertical {
  id: string;
  markets: string[];
  titleEn: string;
  titleHe: string;
  avgRecoveryMinor: number;
  currency: string;
  monetization: MonetizationModel;
  status: VerticalStatus;
  /** In-app path when one exists. */
  route?: string;
  /** Global pack right id (market-specific prefix applied at runtime). */
  packRightId?: string;
  citation?: string;
}

export const REVENUE_VERTICALS: readonly RevenueVertical[] = [
  {
    id: "il_telecom_agent",
    markets: ["IL"],
    titleEn: "Mobile / internet bill negotiation",
    titleHe: "התאמת חשבון סלולר ואינטרנט",
    avgRecoveryMinor: 1_800_000,
    currency: "ILS",
    monetization: "success_fee",
    status: "live_agent",
    route: "/money",
  },
  {
    id: "il_subscription_cancel",
    markets: ["IL"],
    titleEn: "Subscription cancel or retention discount",
    titleHe: "ביטול מנוי או הנחת שימור",
    avgRecoveryMinor: 840_000,
    currency: "ILS",
    monetization: "success_fee",
    status: "live_agent",
    route: "/cancel",
  },
  {
    id: "il_electricity",
    markets: ["IL"],
    titleEn: "Electricity supplier switch / social tariff",
    titleHe: "חשמל — מעבר ספק או תעריף מוזל",
    avgRecoveryMinor: 1_200_000,
    currency: "ILS",
    monetization: "success_fee",
    status: "live_agent",
    route: "/electricity",
  },
  {
    id: "gb_student_loan_overpayment",
    markets: ["GB"],
    titleEn: "UK student loan overpayment refund",
    titleHe: "החזר יתר על הלוואת סטודנטים (בריטניה)",
    avgRecoveryMinor: 24_000,
    currency: "GBP",
    monetization: "success_fee",
    status: "letter_pack",
    route: "/student-loan-overpayment",
    packRightId: "student_loan_overpayment",
    citation: "SLC repayment account / Education (Student Loans) Regulations 1998",
  },
  {
    id: "us_wage_theft",
    markets: ["US"],
    titleEn: "Unpaid wages / overtime (FLSA)",
    titleHe: "שכר גנוב ושעות נוספות (ארה״ב)",
    avgRecoveryMinor: 50_000_00,
    currency: "USD",
    monetization: "success_fee",
    status: "letter_pack",
    route: "/wage-statement-audit",
    packRightId: "wage_statement_audit",
  },
  {
    id: "us_fdcpa",
    markets: ["US"],
    titleEn: "Debt collector statutory violations (FDCPA)",
    titleHe: "הפרות חוק גביית חוב (FDCPA)",
    avgRecoveryMinor: 1_000_00,
    currency: "USD",
    monetization: "success_fee",
    status: "letter_pack",
    route: "/debt-collector-dispute",
    packRightId: "fdcpa_debt_validation",
    citation: "15 U.S.C. § 1692k",
  },
  {
    id: "eu_train_delay",
    markets: ["GB", "DE", "FR"],
    titleEn: "Train delay compensation (EU/UK passenger rights)",
    titleHe: "פיצוי על עיכוב רכבת",
    avgRecoveryMinor: 25_00,
    currency: "EUR",
    monetization: "success_fee",
    status: "rights_only",
    route: "/train-delay",
    citation: "EU Regulation 1371/2007 / UK National Rail conditions",
  },
  {
    id: "il_bank_fees",
    markets: ["IL"],
    titleEn: "Bank fee waiver / basic track",
    titleHe: "עמלות בנק / מסלול בסיסי",
    avgRecoveryMinor: 600_00,
    currency: "ILS",
    monetization: "success_fee",
    status: "live_agent",
    route: "/bank-fees",
  },
  {
    id: "il_deposit_return",
    markets: ["IL"],
    titleEn: "Rental deposit not returned",
    titleHe: "פיקדון שכירות שלא הוחזר",
    avgRecoveryMinor: 5_000_00,
    currency: "ILS",
    monetization: "success_fee",
    status: "live_agent",
    route: "/deposit",
  },
  {
    id: "il_consumer_cancel14",
    markets: ["IL"],
    titleEn: "14-day remote sale cancellation (gym, courses)",
    titleHe: "ביטול עסקה מרחוק תוך 14 יום",
    avgRecoveryMinor: 800_00,
    currency: "ILS",
    monetization: "success_fee",
    status: "letter_pack",
    route: "/consumer-cancel",
    packRightId: "consumer_cancel14",
    citation: "חוק הגנת הצרכן, התשמ״א-1981, סעיף 14ג",
  },
  {
    id: "il_collection_complaint",
    markets: ["IL"],
    titleEn: "Debt collector harassment / verify debt",
    titleHe: "גובה חוב — תלונה ואימות",
    avgRecoveryMinor: 0,
    currency: "ILS",
    monetization: "success_fee",
    status: "letter_pack",
    route: "/collection-complaint",
    packRightId: "collection_agency_complaint_il",
    citation: "חוק הגנת הצרכן, התשמ״א-1981",
  },
  {
    id: "il_car_insurance_refund",
    markets: ["IL"],
    titleEn: "Car insurance pro-rata refund",
    titleHe: "החזר פרמיית ביטוח רכב",
    avgRecoveryMinor: 1_200_00,
    currency: "ILS",
    monetization: "success_fee",
    status: "letter_pack",
    route: "/car-insurance-refund",
    packRightId: "car_insurance_pro_rata_refund",
    citation: "חוק חוזי הביטוח, התשמ״א-1981",
  },
  {
    id: "il_toll_dispute",
    markets: ["IL"],
    titleEn: "Highway 6 toll appeal",
    titleHe: "ערעור חיוב כביש 6",
    avgRecoveryMinor: 200_00,
    currency: "ILS",
    monetization: "success_fee",
    status: "letter_pack",
    route: "/toll-dispute",
    packRightId: "route6_dispute",
  },
  {
    id: "il_vehicle_license_refund",
    markets: ["IL"],
    titleEn: "Vehicle licence fee prorated refund",
    titleHe: "החזר אגרת רישוי רכב",
    avgRecoveryMinor: 400_00,
    currency: "ILS",
    monetization: "success_fee",
    status: "letter_pack",
    route: "/vehicle-license-refund",
    packRightId: "vehicle_license_fee_refund",
  },
  {
    id: "il_train_delay",
    markets: ["IL"],
    titleEn: "Israel Railways delay compensation",
    titleHe: "פיצוי עיכוב רכבת ישראל",
    avgRecoveryMinor: 50_00,
    currency: "ILS",
    monetization: "success_fee",
    status: "letter_pack",
    route: "/train-delay",
    packRightId: "train_delay_compensation",
  },
  {
    id: "il_vaad_bait",
    markets: ["IL"],
    titleEn: "HOA / building committee charge transparency",
    titleHe: "פירוט חיובי ועד בית",
    avgRecoveryMinor: 3_000_00,
    currency: "ILS",
    monetization: "success_fee",
    status: "letter_pack",
    route: "/vaad-bait",
    packRightId: "vaad_bait_accounting_il",
    citation: "חוק המקרקעין, התשכ״ט-1969 — תקנות ועדי בתים",
  },
  {
    id: "il_water_leak",
    markets: ["IL"],
    titleEn: "Concealed water leak credit",
    titleHe: "הנחה בגין נזילה סמויה",
    avgRecoveryMinor: 800_00,
    currency: "ILS",
    monetization: "success_fee",
    status: "letter_pack",
    route: "/water-bill",
    packRightId: "water_leak_credit",
  },
  {
    id: "il_rental_repairs",
    markets: ["IL"],
    titleEn: "Essential rental repairs demand",
    titleHe: "תיקון ליקוי בדירה שכורה",
    avgRecoveryMinor: 0,
    currency: "ILS",
    monetization: "success_fee",
    status: "letter_pack",
    route: "/landlord-repairs",
    packRightId: "rental_essential_repairs_il",
    citation: "חוק השכירות והשאילה, התשל״ג-1973",
  },
  {
    id: "il_duplicate_charge",
    markets: ["IL"],
    titleEn: "Duplicate or wrong card charge",
    titleHe: "חיוב כפול או שגוי",
    avgRecoveryMinor: 200_00,
    currency: "ILS",
    monetization: "success_fee",
    status: "letter_pack",
    route: "/duplicate-charge",
    packRightId: "duplicate_charge_dispute",
  },
  {
    id: "il_telecom_exit",
    markets: ["IL"],
    titleEn: "Telecom disconnect and post-disconnect refunds",
    titleHe: "ניתוק תקשורת והחזר חיובים",
    avgRecoveryMinor: 150_00,
    currency: "ILS",
    monetization: "success_fee",
    status: "letter_pack",
    route: "/telecom-exit",
    packRightId: "consumer_telecom_exit",
    citation: "חוק התקשורת (בזק ושידורים), התשמ״ב-1982",
  },
  {
    id: "il_consumer_warranty",
    markets: ["IL"],
    titleEn: "Product warranty repair or replacement",
    titleHe: "מימוש אחריות מוצר",
    avgRecoveryMinor: 500_00,
    currency: "ILS",
    monetization: "success_fee",
    status: "letter_pack",
    route: "/warranty",
    packRightId: "consumer_warranty_il",
    citation: "חוק הגנת הצרכן, התשמ״א-1981",
  },
  {
    id: "il_arnona",
    markets: ["IL"],
    titleEn: "Arnona discount / appeal",
    titleHe: "הנחה או ערעור ארנונה",
    avgRecoveryMinor: 2_400_00,
    currency: "ILS",
    monetization: "success_fee",
    status: "rights_only",
    route: "/arnona",
  },
  {
    id: "mandate_verification",
    markets: ["*"],
    titleEn: "Mandate verify + decide (institutional)",
    titleHe: "אימות והחלטת Mandate למוסדות",
    avgRecoveryMinor: 0,
    currency: "USD",
    monetization: "network_verification",
    status: "live_agent",
    route: "/en/institutions",
  },
  {
    id: "oracle_predict",
    markets: ["*"],
    titleEn: "Calibrated claim outcome prediction",
    titleHe: "חיזוי תוצאת תביעה מכויל",
    avgRecoveryMinor: 0,
    currency: "USD",
    monetization: "oracle_api",
    status: "live_agent",
    citation: "De-identified StrategyOutcome graph",
  },
] as const;

export function revenueVerticalsForMarket(market: string): RevenueVertical[] {
  const upper = market.toUpperCase();
  return REVENUE_VERTICALS.filter((v) => v.markets.includes("*") || v.markets.includes(upper));
}
