import { NextResponse } from "next/server";
import { aiAvailable, aiProvider } from "@/lib/ai";

export const dynamic = "force-dynamic";

export async function GET() {
  return NextResponse.json({
    ok: true,
    name: "zakai",
    version: "0.9.0",
    buildMarker: "electricity-full-household-agent-rounds-pilot-2026-07-28",
    positioning: "standard consumer money agent + Mandate infrastructure",
    tracks: {
      consumer: "problem-first entry · Money OS · agent recovery loop · viral after SAVED · household",
      infrastructure: "Ed25519 Mandate standard · JWKS · B2B embed multi-path · institutional verify · pilot intake",
    },
    ai: { available: aiAvailable(), provider: aiProvider() },
    markets: ["IL", "GB", "US", "DE", "FR", "CA"],
    features: {
      moneyOs: true,
      fromScanCase: true,
      fromScanBatch: true,
      scanOneClick: true,
      sentCronNudge: true,
      cancelPrefill: true,
      mandate: true,
      mandateQr: true,
      mandatePdf: true,
      mandateSharedDoc: true,
      mandateAttachOnFollowUp: true,
      overnightAgent: true,
      agentAutoApprove: true,
      agentAutoFollowUp: true,
      agentFollowUpRounds: true,
      agentFollowUpCooldownFix: true,
      agentDispatchOneTap: true,
      ownershipAutoMandate: true,
      recheckReminders: true,
      competitorFollowUp: true,
      documentVault: true,
      yearWrapped: true,
      publicProofWall: true,
      householdMode: true,
      airlineCase: true,
      refundChaseCase: true,
      bankFeesCase: true,
      parkingCase: true,
      transportFineCase: true,
      electricityFullCase: true,
      b2bEmbed: true,
      b2bEmbedMultiPath: true,
      viralAfterSaved: true,
      leaksDemandEngine: true,
      globalMarketsStrip: true,
      inboundEmailProof: true,
      inboundEmailRateLimit: true,
      proofsForwardUx: true,
      webPush: true,
      enablePushUi: true,
      proposedSavingOneTap: true,
      strategyInsights: true,
      ownershipMagicLink: true,
      allIlVerticalsFull: true,
      deFrCaPacksDeep: true,
      problemFirstHomepage: true,
      dualTrackBusinessPage: true,
      whatAmIOwedActionDoors: true,
      usPackDeep: true,
      dualTrackNav: true,
      embedPathAwarePreview: true,
      emptyDashboardProblemDoors: true,
      priorityAgenticBoost: true,
      openapiInstitutional: true,
      b2bDualTrackLeads: true,
      agentRoundVisibility: true,
      institutionalPilotCta: true,
      monthlyDigestOpenSent: true,
    },
    time: new Date().toISOString(),
  });
}
